/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppAdd {
    'history': RouterHistory;
  }
  interface AppAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface AppFetchId {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppFetchIdAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppFetch {
    'load': () => void;
    'name': string;
  }
  interface AppFetchAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppAdd': Components.AppAdd;
    'AppFetchId': Components.AppFetchId;
    'AppFetch': Components.AppFetch;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-add': Components.AppAddAttributes;
    'app-fetch-id': Components.AppFetchIdAttributes;
    'app-fetch': Components.AppFetchAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppAddElement extends Components.AppAdd, HTMLStencilElement {}
  var HTMLAppAddElement: {
    prototype: HTMLAppAddElement;
    new (): HTMLAppAddElement;
  };

  interface HTMLAppFetchIdElement extends Components.AppFetchId, HTMLStencilElement {}
  var HTMLAppFetchIdElement: {
    prototype: HTMLAppFetchIdElement;
    new (): HTMLAppFetchIdElement;
  };

  interface HTMLAppFetchElement extends Components.AppFetch, HTMLStencilElement {}
  var HTMLAppFetchElement: {
    prototype: HTMLAppFetchElement;
    new (): HTMLAppFetchElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-add': HTMLAppAddElement
    'app-fetch-id': HTMLAppFetchIdElement
    'app-fetch': HTMLAppFetchElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-add': HTMLAppAddElement;
    'app-fetch-id': HTMLAppFetchIdElement;
    'app-fetch': HTMLAppFetchElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
